### ISSUE TITLE
Are the option counts grouped by Stock Plan or by underlying instrument?

### ISSUE THREAD

**Issue by pjohnmeyer** [Open-Cap-Table-Coalition/ocx#25]
In v0.4 of the reference Stakeholder Snapshot sheet, the "Stock Options" column looks like this:

![image](https://user-images.githubusercontent.com/122016/233648504-785847f2-7ec5-419d-a31d-3ba36554368d.png)

but the name of the stock plan on the Context sheet is "Startup, Inc.2018 Stock Plan"

**Does the header imply that we group all options by underlying instrument, and not stock plan?** In other words, if there were two Stock Plans that both convert to Class A Common, would there be one "Class A Common" column on the Stakeholder Snapshot sheet that lumps both together, or would there be a separate column for each Stock Plan?

**Comment by dbierut** [comment]
The LFWG had proposed organizing the option details by each separate Plan in the Summary Snapshot page - if the company had two separate equity incentive plans, we'd have bold headings for each and have a breakdown of outstanding + available for the different securities authorized under that specific plan. 

That being the case, it makes sense to me to organize the Stakeholder Snapshot the same way - e.g. a column for 2018 Plan Class A Common Stock Options; then separate column for _2020 Plan_ Class A Common Stock Options; a separate column for 2020 Plan _Class B_ Common Options (if applicable); and so on.

**Comment by pjohnmeyer** [comment]
Great; we are implementing it this way in #17 and #18 already.
